### PR TITLE
Run HTML message body through make_clickable(). #915

### PR DESCRIPTION
**Pull request by mindctrl**
#915

### CODE REVIEW

**Comment by nosegraze** [comment]
It doesn't really matter of course, but I wonder if it would be better to stick it in the `text_to_html()` method. Like:

```
$message = make_clickable( wpautop( $message ) );
```

It's still relevant to what's happening in that method IMO (text to HTML) and means the check only has to happen once.

**Comment by mindctrl** [comment]
@nosegraze I tried that and it didn't work for the Group Account emails. I didn't dig deeper to figure out why.

**Comment by mindctrl** [comment]
Hmm it might have been on an older Group Accounts version. Not sure. I'll look at it again later.

**Comment by nosegraze** [comment]
Works perfectly for me!

**Pull request merged**
