### PR TITLE
Update Stripe library to 6.1.0

### LINKED ISSUE #522: Update Stripe API libraries
It's time to get them up to date.

### PR DESCRIPTION
**Pull request by tnorthcutt**
Does not include the following directories and files that were in the Stripe library, as these were also not included the last time the library was updated in RCP:
```
.github/
examples/
tests/
.coveralls.yml
.gitignore
.travis.yml
build.php
```

Closes #522

### CODE REVIEW

**Comment by mindctrl** [comment]
@nosegraze thanks! Did you happen to test PHP 5.3?

**Comment by nosegraze** [comment]
I tested with `5.3.10` and it worked fine.

**Comment by mindctrl** [comment]
Merged. Thanks @tnorthcutt and @nosegraze!

**Comment by tnorthcutt** [comment]
🎉

**Pull request merged**
