### PR TITLE
Apply a filter to the restrict option dropdown

### PR DESCRIPTION
**Pull request by joshuadavidnelson**
I'm hoping to expand these "restrict by" options for a client (working on a "restrict by group" add-on to work with the Group Account extension), but I figure this will be handy for others as well. There's probably a better way to build this out, and this doesn't address the javascript related to the viewing of the sub options. Appreciate consideration/input.

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Great idea for sure. My one concern, however, is that in order to really use custom options here (at least in an intuitive way) there also needs to be some custom JS written to hide/show appropriate elements.

Any thoughts or concerns with that?

**Comment by joshuadavidnelson** [comment]
I completely agree. I looked at the JavaScript associated with this, but my skills there are a little weaker, so I thought I'd start here and test the waters before diving in further.

My approach would be to associate the dropdown value to a wrapper div with the custom options. So, you'd extend it by using the after hook to add associated custom fields wrapped by a div with an appropriate id. Looks like the javascript is written to reference the specific elements and dropdown values, so I'd update it to be more universal. Any other way you'd rather I do it?

**Comment by mindctrl** [comment]
I like the idea, but I have a couple concerns.

First, because we just changed this UI in version 2.6 and had to make a couple bug fixes afterwards, I'm concerned we may introduce a bug here or otherwise make it more brittle. I'd rather this bake for while before making it more flexible.

Second, with several of our own add-ons adjusting content visibility, adding more flexibility adds more complexity and things we may need to consider, maintain, and test. It may end up not being an issue, but something we need to consider.

For JS, we should probably add some triggers to our existing JS to make that part easier to tie into.

With regards to 'restrict by group' functionality, that's a cool idea. I think it's a good idea for the Group Accounts add-on itself, as opposed to another add-on. @joshuadavidnelson would you be interested in contributing the feature to the Group Accounts add-on directly?

**Comment by joshuadavidnelson** [comment]
John, all good points - I had a feeling such a change would bring up things like this.

In regards to contributing to the Group Accounts add-on - Yes, absolutely! I didn't see a repo for it, so I took a stab here to get the ball rolling. I agree it would make more sense to be part of that add-on than an add-on-to-an-add-on. ;-)

Let me know the best way for me to proceed if we go that route. Appreciate the consideration and flexibility!

**Comment by mindctrl** [comment]
@joshuadavidnelson great! Sent you an invitation to the Group Accounts repo.

**Comment by joshuadavidnelson** [comment]
@mindctrl Awesome, thanks! I'll issue a PR there sometime later this week, likely. In regards to the UI, do we shelf the idea of extending this dropdown or is there another approach I should use?

**Comment by mindctrl** [comment]
@joshuadavidnelson let's leave this open for now. I'll think about this a bit and see what I come up with. Feel free to shoot me a message at restrictcontentpro.com/support if you'd like to chat directly.

**Comment by joshuadavidnelson** [comment]
@mindctrl Sounds good. Thanks!

**Pull request closed without merging**
