### PR TITLE
update rcp_stripe_update_discount() to use args passed from action

### PR DESCRIPTION
**Pull request by bearded-avenger**
This function should utilize the args passed in from the action instead of $_POST fields.

### CODE REVIEW

**Comment by bearded-avenger** [comment]
Note: ideally rcp_stripe_create_discount() should also be updated to use those args as well

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Thanks!

**Comment by michaelbeil** [comment]
Oh great bearded one, we thank thee for thine gift.

**Pull request merged**
