### PR TITLE
Add restriction options to add taxonomy term form - issue/497

### PR DESCRIPTION
**Pull request by pippinsplugins**
WIP.

Also renames functions / file to be generic instead of for categories. #497

### CODE REVIEW

**Comment by mindctrl** [comment]
@pippinsplugins anything else you wanted to do here?

**Comment by pippinsplugins** [comment]
@mindctrl I don't believe it's 100% working yet. Need to relook at it.

**Comment by mindctrl** [comment]
Updated this to hook into `created_term` to save on new term creation. One thing I noticed about the UX, which is really a WP core thing I guess, is if you have enough levels to push the top of the screen out of view, when you click `Add New Category` you can't tell that the term was added. We may need to figure out a workaround for this.

**Comment by mindctrl** [comment]
Circled back around to this with some fresher eyes. I removed the table markup here, since there's no table we're inserting into already. I matched the core convention with `<div>` wrappers around each "section". That made things cleaner looking.

**Comment by pippinsplugins** [comment]
This works great.

**Pull request merged**
