### PR TITLE
Release/2.5

### PR DESCRIPTION
**Pull request by pippinsplugins**
2.5 release.

Before this is merged in, we need to test everything extensive. Each bug / feature in this release has been tested already, some together and some independently, but we need to test everything as a whole. The checklist below represents the primary areas that need tested.

Some of the items below overlap but I've separated them in order to be thorough.

### One time payments

Please test each gateway with a one time payment. No discounts, sign up fees, or proration credits.

- [x] Stripe
- [x] Stripe Checkout
- [x] PayPal Standard
- [x] PayPal Express
- [x] PayPal Pro
- [x] 2Checkout

### Recurring payments

Please test each gateway with a recurring signup. No discounts, sign up fees, or proration credits.

- [x] Stripe
- [x] Stripe Checkout
- [x] PayPal Standard
- [x] PayPal Express
- [x] PayPal Pro
- [x] 2Checkout

### Recurring payments with a discount code

Please test each gateway with a discount code. No sign up fees, or proration credits.

- [x] Stripe
- [x] Stripe Checkout
- [x] PayPal Standard
- [x] PayPal Express
- [x] PayPal Pro
- [x] 2Checkout

### One time payments with a discount code

Please test each gateway with a discount code. No sign up fees, or proration credits.

- [x] Stripe
- [x] Stripe Checkout
- [x] PayPal Standard
- [x] PayPal Express
- [x] PayPal Pro
- [x] 2Checkout

### Recurring payments with a pro-ration

Please test each gateway with a pro-ration credit.

- [x] Stripe
- [x] Stripe Checkout
- [x] PayPal Standard
- [x] PayPal Express
- [x] PayPal Pro
- [x] 2Checkout

### One time payments with a pro-ration

Please test each gateway with a pro-ration credit.

- [x] Stripe
- [x] Stripe Checkout
- [x] PayPal Standard
- [x] PayPal Express
- [x] PayPal Pro
- [x] 2Checkout

### Upgrade / downgrade

Please test upgrading and downgrading between subscription levels.

- [x] Upgrade daily to monthly or yearly
- [x] Upgrade monthly to monthly
- [x] Upgrade monthly to lifetime
- [x] Downgrade monthly to daily
- [x] Downgrade yearly to monthly
- [x] Downgrade lifetime to monthly (should this be possible?)
- [x] Upgrade from one time to recurring
- [x] Account never ends up as cancelled after upgrade
- [x] Sub cancelled alert not sent to admin during upgrade

### Discount Codes

- [x] Percentage discount codes less than 100
- [x] 100% discount codes
- [x] Flat rate discount codes less than the subscription price
- [x] Flat rate discount codes equal to or greater than the subscription price
- [x] Discount codes on recurring sign up
- [x] Discount codes on one-time sign up

### WooCommerce integration

- [x] Restrict product visibility
- [x] Restrict ability to purchase product
- [x] Catalogue view restrictions
- [x] Single product page restrictions

### WP Approve User integration

- [x] Viewing restricted page before being approved
- [x] Viewing restricted page after being approved
- [x] Viewing non-restricted page before being approved
- [x] Viewing non-restricted page after being approved

### Stripe Checkout

- [x] Sign up through [register_form]
- [x] Sign up through [register_form id="x"]
- [x] Sign up through [register_form_stripe id="x"]

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Recurring signups through 2Checkout do not work. They get flagged as `one-time` in 2Checkout.

**Comment by pippinsplugins** [comment]
False alarm, they do work. 2Checkout does not support daily subscriptions. They support Week, Month, and Year:
```
Sets billing frequency. Ex. ‘1 Week’ to bill order once a week. (Can use # Week, # Month or # Year) Required for recurring lineitems.
```

**Comment by mindctrl** [comment]
re: lifetime > monthly. RCP doesn't create a customer record in Stripe when doing one-time purchases, which is what a lifetime sub is. If you make a lifetime purchase then buy a subscription with the same account, a customer record is created, but the customer's previous payment isn't linked to the customer record in Stripe. Don't know if we care about this right now.

**Comment by pippinsplugins** [comment]
@mindctrl I noticed that as well. For now I vote we do not address it. We can try and address it later. All charges still go through properly.

**Pull request merged**
