### PR TITLE
issue/1266

### PR DESCRIPTION
**Pull request by marcperel**
Adding a filter to the user role dropdown in the rcp_user_level meta field. This allows plugins to add their own user roles to this field, currently it's hardcoded with WP defaults.

### CODE REVIEW

**Comment by mindctrl** [comment]
Custom roles are coming in 2.9.

**Comment by marcperel** [comment]
Thanks @mindctrl appreciate the swift response, should likely have investigated this further.

**Comment by mindctrl** [comment]
@marcperel they're in the `release/2.9` branch if you want to give it a whirl.

**Comment by marcperel** [comment]
Thanks I'm on it meow.

**Pull request closed without merging**
